In [14]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [15]:
def A(r):
  return (r+1)**2

In [16]:
# Constants
Ti = 15 # K
To = 5 # K
k = 1.4 # W/mK
L = 5*10**(-3) # m 
B = 1 # m^2
node = 10
intervall = node - 1
delta_x = L/(intervall)
r = 0

print(delta_x)

0.0005555555555555556


In [17]:
zero_data = np.zeros(shape=(node,node))
st_mat = pd.DataFrame(zero_data, columns= [i for i in range(1,node + 1)], index = [i for i in range(1,node + 1)])
st_mat

1    2    3    4    5    6    7    8    9    10
1   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
3   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
4   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
5   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
6   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
7   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
8   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
9   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
10  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

In [18]:
for i in range(1,node):
  matrix = pd.DataFrame([[k*A(r)/delta_x, -k*A(r)/delta_x], [-k*A(r)/delta_x, k*A(r)/delta_x]], index = [i,i+1], columns = [i,i+1])
  st_mat = matrix.add(st_mat, fill_value=0)
  r += delta_x
st_mat 


1            2            3            4            5            6   \
1   2520.0 -2520.000000     0.000000     0.000000     0.000000     0.000000   
2  -2520.0  5042.800778 -2522.800778     0.000000     0.000000     0.000000   
3      0.0 -2522.800778  5048.403889 -2525.603111     0.000000     0.000000   
4      0.0     0.000000 -2525.603111  5054.010111 -2528.407000     0.000000   
5      0.0     0.000000     0.000000 -2528.407000  5059.619444 -2531.212444   
6      0.0     0.000000     0.000000     0.000000 -2531.212444  5065.231889   
7      0.0     0.000000     0.000000     0.000000     0.000000 -2534.019444   
8      0.0     0.000000     0.000000     0.000000     0.000000     0.000000   
9      0.0     0.000000     0.000000     0.000000     0.000000     0.000000   
10     0.0     0.000000     0.000000     0.000000     0.000000     0.000000   

             7            8            9            10  
1      0.000000     0.000000     0.000000     0.000000  
2      0.000000     0.000000     0.000000     0.000000  
3      0.000000     0.000000     0.000000     0.000000  
4      0.000000     0.000000     0.000000     0.000000  
5      0.000000     0.000000     0.000000     0.000000  
6  -2534.019444     0.000000     0.000000     0.000000  
7   5070.847444 -2536.828000     0.000000     0.000000  
8  -2536.828000  5076.466111 -2539.638111     0.000000  
9      0.000000 -2539.638111  5082.087889 -2542.449778  
10     0.000000     0.000000 -2542.449778  2542.449778

In [19]:
q_vec = np.zeros((node,1))
q_vec

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [20]:
q_vec[1] = - (st_mat.iloc[1,0]  * Ti)
q_vec

array([[    0.],
       [37800.],
       [    0.],
       [    0.],
       [    0.],
       [    0.],
       [    0.],
       [    0.],
       [    0.],
       [    0.]])

In [21]:
q_vec[-2] = (st_mat.iloc[3,2] * To)
q_vec

array([[     0.        ],
       [ 37800.        ],
       [     0.        ],
       [     0.        ],
       [     0.        ],
       [     0.        ],
       [     0.        ],
       [     0.        ],
       [-12628.01555556],
       [     0.        ]])

In [22]:
st_mat = st_mat.iloc[1:-1,1:-1]

In [23]:
q_vec = q_vec[1:-1]


In [24]:
q_vec

array([[ 37800.        ],
       [     0.        ],
       [     0.        ],
       [     0.        ],
       [     0.        ],
       [     0.        ],
       [     0.        ],
       [-12628.01555556]])

In [25]:
np.linalg.solve(st_mat, q_vec)

array([[12.77160153],
       [10.545677  ],
       [ 8.32222229],
       [ 6.10123328],
       [ 3.88270589],
       [ 1.66663602],
       [-0.54698041],
       [-2.75814747]])

In [26]:
st_mat

2            3            4            5            6  \
2  5042.800778 -2522.800778     0.000000     0.000000     0.000000   
3 -2522.800778  5048.403889 -2525.603111     0.000000     0.000000   
4     0.000000 -2525.603111  5054.010111 -2528.407000     0.000000   
5     0.000000     0.000000 -2528.407000  5059.619444 -2531.212444   
6     0.000000     0.000000     0.000000 -2531.212444  5065.231889   
7     0.000000     0.000000     0.000000     0.000000 -2534.019444   
8     0.000000     0.000000     0.000000     0.000000     0.000000   
9     0.000000     0.000000     0.000000     0.000000     0.000000   

             7            8            9  
2     0.000000     0.000000     0.000000  
3     0.000000     0.000000     0.000000  
4     0.000000     0.000000     0.000000  
5     0.000000     0.000000     0.000000  
6 -2534.019444     0.000000     0.000000  
7  5070.847444 -2536.828000     0.000000  
8 -2536.828000  5076.466111 -2539.638111  
9     0.000000 -2539.638111  5082.087889